"""Write SWEVO_manuscript_full.tex: the SWEVO main manuscript as ONE LaTeX file.

Every \\input (preamble macros, number macros, section files, generated tables) is inlined, and the floats that
the SWEVO sections place from captured generated files (\\SuppTable, \\AblTable, \\swResFigure) are written out
literally, so the file needs only the figure PDFs (figures_mpce/, figures_final/) and, for the S- references to
the supplementary material, SWEVO_supplement.aux (xr). Usage (from the paper folder):
    python3 analysis/flatten_swevo.py [out.tex]
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
CAPTURED = ['analysis/mpce_supplementary.tex', 'analysis/mpce_supp_diag.tex', 'analysis/mpce_supp_inference.tex',
            'analysis/mpce_tab_split.tex', 'analysis/mpce_supp_direction.tex', 'analysis/mpce_supp_csweep.tex']


def code_part(line):
    """(code, comment) split of a line at the first unescaped %."""
    m = re.search(r'(?<!\\)%', line)
    return (line, '') if not m else (line[:m.start()], line[m.start():])


def texfile(name):
    return name if name.endswith('.tex') else name + '.tex'


def flatten(path, depth=0):
    out = [f'% >>>>> begin {path}\n'] if depth else []
    for line in open(path, encoding='utf-8'):
        code, comment = code_part(line.rstrip('\n'))
        m = re.fullmatch(r'\s*\\IfFileExists\{([^}#]+)\}\{\\input\{([^}#]+)\}\}\{\}\s*', code)
        if m:
            f = texfile(m.group(2))
            out.append(''.join(flatten(f, depth + 1)) if os.path.exists(f) else f'% (absent: {f})\n')
            continue
        m = re.fullmatch(r'\s*\\input\{([^}#]+)\}\s*', code)
        if m:
            out += flatten(texfile(m.group(1)), depth + 1)
            continue
        out.append(line if line.endswith('\n') else line + '\n')
    if depth:
        out.append(f'% <<<<< end {path}\n')
    return out


def float_body(label):
    """Body (between \\begin{env}[..] and \\end{env}) of the generated float whose first \\label is `label`."""
    for f in CAPTURED:
        s = open(f, encoding='utf-8').read()
        for m in re.finditer(r'\\begin\{(table\*?|figure\*?)\}(\[[^\]]*\])?', s):
            env = m.group(1)
            end = s.index('\\end{%s}' % env, m.end())
            body = s[m.end():end]
            first = re.search(r'\\label\{([^}]+)\}', body)
            if first and first.group(1) == label:
                return body.strip('\n') + '\n', f
    sys.exit(f'float {label} not found in the captured files')


def place(text):
    out = []
    for line in text.split('\n'):
        code, comment = code_part(line)
        calls = re.findall(r'\\(?:CaptureSuppTables|swResCaptureFigs)\{[^}#]+\}', code)
        if calls:  # captures typeset nothing; their floats are written out where they are placed
            code = re.sub(r'\\(?:CaptureSuppTables|swResCaptureFigs)\{[^}#]+\}', '', code)
            comment = (comment or '%') + ' [flattened: removed ' + ' '.join(calls) + ']'

        def rep(m, env, opt):
            body, src = float_body(m.group('lab'))
            o = opt(m)
            return (f'%\n% --- float {m.group("lab")} from {src}\n\\begin{{{env}}}[{o}]\n{body}\\end{{{env}}}\n')
        new = re.sub(r'\\SuppTable\{(?P<lab>[^}#]+)\}', lambda m: rep(m, 'table', lambda _: '!htbp'), code)
        new = re.sub(r'\\AblTable(?:\[(?P<o>[^\]]*)\])?\{(?P<lab>[^}#]+)\}',
                     lambda m: rep(m, 'table', lambda mm: mm.group('o') or '!t'), new)
        new = re.sub(r'\\swResFigure\{(?P<lab>[^}#]+)\}', lambda m: rep(m, 'figure*', lambda _: '!t'), new)
        out.append(new + comment)
    return '\n'.join(out)


out = sys.argv[1] if len(sys.argv) > 1 else 'SWEVO_manuscript_full.tex'
text = ''.join(flatten('SWEVO_manuscript.tex'))
text = place(text)
head = ('% SWEVO_manuscript_full.tex -- single-file version of SWEVO_manuscript.tex, generated by analysis/flatten_swevo.py.\n'
        '% All \\input files and the generated tables and figures placed in the text are inlined. Needs: figures_mpce/,\n'
        '% figures_final/ and (for references to the supplementary material, prefix S-) SWEVO_supplement.aux.\n')
open(out, 'w', encoding='utf-8').write(head + text)
print(out, len(text.splitlines()), 'lines')
